
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DELETE ID INT RECAP STRING UPDATEresultado : s STRINGs : INTs : IDs : STRING s : ADDs : DELETEs : UPDATEs : RECAP'
    
_lr_action_items = {'INT':([0,],[4,]),'ID':([0,],[5,]),'STRING':([0,2,3,4,5,6,7,8,9,],[3,10,-4,-2,-3,-5,-6,-7,-8,]),'ADD':([0,],[6,]),'DELETE':([0,],[7,]),'UPDATE':([0,],[8,]),'RECAP':([0,],[9,]),'$end':([1,10,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'resultado':([0,],[1,]),'s':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> resultado","S'",1,None,None,None),
  ('resultado -> s STRING','resultado',2,'p_resultado','interprete.py',46),
  ('s -> INT','s',1,'p_expr_num','interprete.py',61),
  ('s -> ID','s',1,'p_expr_id','interprete.py',65),
  ('s -> STRING','s',1,'p_expr_string','interprete.py',73),
  ('s -> ADD','s',1,'p_agregar','interprete.py',77),
  ('s -> DELETE','s',1,'p_eliminar','interprete.py',81),
  ('s -> UPDATE','s',1,'p_update','interprete.py',85),
  ('s -> RECAP','s',1,'p_resumir','interprete.py',89),
]
